# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c135d9553e44471a9c6bb0a0c752a6a37baf2d51b07d2963ad76a81b8d4f1a2edd3bee2850fc35f5ac3f1e8aec6b9b8bd301b7f9e7a9ee45acc0db814767bcf6

test:
  secret_key_base: f6c6c3f59e680054eab15ba4582b9ef68f706937cdacc38e46b721f7bb78ec84d2f9a0ecf8e5261af0887df4949b4f094a494f778f65aa4486c1b2e2cd05971e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
